import { AfterViewInit, Directive, ElementRef, NgZone, OnDestroy } from '@angular/core';

@Directive({selector:'table',standalone:true})
export class SortableTableDirective implements AfterViewInit,OnDestroy {
  private observer?:MutationObserver; private active=-1; private direction:1|-1=1;
  private click=(event:Event)=>{const header=(event.target as HTMLElement).closest('th') as HTMLTableCellElement|null;if(!header||!header.classList.contains('sortable-column'))return;const row=header.parentElement as HTMLTableRowElement,index=Array.from(row.cells).indexOf(header);if(index<0)return;this.direction=this.active===index?(this.direction===1?-1:1):1;this.active=index;this.sort(index,this.direction);this.decorate();};
  constructor(private host:ElementRef<HTMLTableElement>,private zone:NgZone){}
  ngAfterViewInit(){this.decorate();this.zone.runOutsideAngular(()=>{this.host.nativeElement.addEventListener('click',this.click);this.observer=new MutationObserver(()=>this.decorate());this.observer.observe(this.host.nativeElement,{childList:true,subtree:true});});}
  ngOnDestroy(){this.host.nativeElement.removeEventListener('click',this.click);this.observer?.disconnect();}
  private decorate(){const headers=Array.from(this.host.nativeElement.querySelectorAll('th'));headers.forEach(header=>{const index=header.cellIndex,text=(header.childNodes[0]?.textContent||header.textContent||'').trim().toLowerCase(),sortable=!!text&&!['action','actions'].includes(text)&&!header.hasAttribute('data-no-sort');header.classList.toggle('sortable-column',sortable);header.setAttribute('aria-sort',this.active===index?(this.direction===1?'ascending':'descending'):'none');let icon=header.querySelector('.table-sort-icon') as HTMLElement|null;if(sortable&&!icon){icon=document.createElement('span');icon.className='table-sort-icon';icon.setAttribute('aria-hidden','true');header.appendChild(icon);}const symbol=this.active===index?(this.direction===1?'▲':'▼'):'⇅';if(icon&&icon.textContent!==symbol)icon.textContent=symbol;});}
  private sort(index:number,direction:1|-1){const body=this.host.nativeElement.tBodies[0];if(!body)return;const rows=Array.from(body.rows).filter(row=>!row.querySelector('th')),groups:{main:HTMLTableRowElement;details:HTMLTableRowElement[]}[]=[];for(const row of rows){const detail=row.cells.length===1&&row.cells[0].colSpan>1;if(detail&&groups.length)groups[groups.length-1].details.push(row);else groups.push({main:row,details:[]});}groups.sort((a,b)=>this.compare(a.main.cells[index]?.innerText||'',b.main.cells[index]?.innerText||'')*direction);groups.forEach(group=>{body.appendChild(group.main);group.details.forEach(row=>body.appendChild(row));});}
  private compare(left:string,right:string){const a=left.trim(),b=right.trim(),an=Number(a.replace(/[^0-9.-]/g,'')),bn=Number(b.replace(/[^0-9.-]/g,''));if(a&&b&&Number.isFinite(an)&&Number.isFinite(bn)&&/\d/.test(a)&&/\d/.test(b))return an-bn;const ad=Date.parse(a),bd=Date.parse(b);if(!Number.isNaN(ad)&&!Number.isNaN(bd)&&/[-/:]/.test(a+b))return ad-bd;return a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'});}
}
