package com.ptms.service;
import com.ptms.exception.BusinessRuleException;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class NavigationPermissionService{
 private static final List<String>ITEMS=List.of("home","dashboard","issue","register","employees","visitors","inventory","remaining","reports","settings");private static final String ADMIN_DEFAULT=String.join(",",ITEMS),SECURITY_DEFAULT="home,dashboard,issue,register,employees,visitors,inventory,remaining,reports";private final JdbcTemplate db;public NavigationPermissionService(JdbcTemplate db){this.db=db;}
 public Map<String,List<String>>defaults(){return Map.of("ADMIN",read("adminNavigationPermissions",ADMIN_DEFAULT),"SECURITY",read("securityNavigationPermissions",SECURITY_DEFAULT));}public List<String>forRole(String role){return"SUPER_USER".equals(role)?ITEMS:defaults().getOrDefault(role,List.of("home"));}
 public Map<String,List<String>>save(Map<String,Object>q){write("adminNavigationPermissions",clean(q.get("ADMIN")));write("securityNavigationPermissions",clean(q.get("SECURITY")));return defaults();}
 public List<String>clean(Object value){if(!(value instanceof Collection<?>values))throw new BusinessRuleException("Navigation permissions must be a list");LinkedHashSet<String>result=new LinkedHashSet<>();result.add("home");for(Object item:values){String key=String.valueOf(item);if(ITEMS.contains(key))result.add(key);}return List.copyOf(result);}
 private List<String>read(String key,String fallback){List<String>values=db.query("select setting_value from app_setting where setting_key=?",(r,n)->r.getString(1),key);String raw=values.isEmpty()?fallback:values.get(0);return Arrays.stream(raw.split(",")).map(String::trim).filter(ITEMS::contains).distinct().toList();}private void write(String key,List<String>values){db.update("insert into app_setting(setting_key,setting_value) values(?,?) on duplicate key update setting_value=values(setting_value)",key,String.join(",",values));}
}
