package com.ptms.service;
import com.ptms.domain.*;import com.ptms.dto.*;import com.ptms.exception.*;import com.ptms.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
@Service @Transactional public class TicketInventoryService {
 private static final Set<Integer>TYPES=Set.of(1,2,4,6,8,12);private final ParkingTicketRepository tickets;private final SettingsService settings;
 public TicketInventoryService(ParkingTicketRepository tickets,SettingsService settings){this.tickets=tickets;this.settings=settings;}
 public List<TicketDto>all(){return tickets.findAll().stream().map(this::dto).toList();}public List<TicketDto>remaining(){LocalDate today=LocalDate.now();return tickets.findByStatusOrderByDurationHoursAscTicketNumberAsc(TicketStatus.AVAILABLE).stream().filter(t->t.getExpiryDate()==null||!t.getExpiryDate().isBefore(today)).map(this::dto).toList();}
 public TicketDto create(TicketDto q){validate(q.barcode(),q.durationHours());String b=normalize(q.barcode());duplicateBarcode(b,null);ParkingTicket t=new ParkingTicket();apply(t,q,b,true);return dto(tickets.save(t));}
 public TicketDto update(Long id,TicketDto q){validate(q.barcode(),q.durationHours());ParkingTicket t=tickets.findById(id).orElseThrow(()->new ResourceNotFoundException("Ticket not found"));String b=normalize(q.barcode());duplicateBarcode(b,id);if(t.getStatus()==TicketStatus.ISSUED&&(q.status()==null||q.status()!=TicketStatus.ISSUED))throw new BusinessRuleException("Issued ticket status cannot be reset from inventory");apply(t,q,b,false);return dto(tickets.save(t));}
 public void delete(Long id){ParkingTicket t=tickets.findById(id).orElseThrow(()->new ResourceNotFoundException("Ticket not found"));if(t.getStatus()==TicketStatus.ISSUED)throw new BusinessRuleException("Issued tickets cannot be deleted");tickets.delete(t);}
 public List<TicketDto>bulk(BulkTicketScanRequest q){List<BulkTicketItemRequest>rows=new ArrayList<>();Integer n=q.startingTicketNumber();for(String b:q.barcodes())if(b!=null&&!b.isBlank()){rows.add(new BulkTicketItemRequest(b,q.physicalTicketNumber(),q.durationHours(),n,q.stockIssueDate(),q.expiryDate()));if(n!=null)n++;}return bulkItems(rows);}
 public List<TicketDto>bulkItems(List<BulkTicketItemRequest>rows){if(rows==null||rows.isEmpty())throw new BusinessRuleException("Add at least one ticket");Set<String>batchBarcodes=new HashSet<>(),batchNumbers=new HashSet<>();Map<String,Integer>nextByCycle=new HashMap<>();List<ParkingTicket>pending=new ArrayList<>();for(BulkTicketItemRequest row:rows){validate(row.barcode(),row.durationHours());validatePeriod(row.durationHours(),row.stockIssueDate(),row.expiryDate());String b=normalize(row.barcode());if(!batchBarcodes.add(b.toLowerCase(Locale.ROOT)))throw new BusinessRuleException("Duplicate barcode in upload: "+b);duplicateBarcode(b,null);LocalDate issue=row.stockIssueDate()==null?LocalDate.now():row.stockIssueDate();String c=cycle(row.durationHours(),issue,row.expiryDate());String sequenceKey=row.durationHours()+"|"+c;int n=row.ticketNumber()==null?nextByCycle.compute(sequenceKey,(k,v)->v==null?nextNumber(row.durationHours(),c):v+1):row.ticketNumber();String key=sequenceKey+"|"+n;if(!batchNumbers.add(key)||tickets.existsByDurationHoursAndTicketNumberCycleAndTicketNumber(row.durationHours(),c,n))throw new BusinessRuleException("Ticket number "+n+" already exists for "+row.durationHours()+" hour tickets in this reset period");ParkingTicket t=new ParkingTicket();t.setBarcode(b);t.setPhysicalTicketNumber(clean(row.physicalTicketNumber()));t.setDurationHours(row.durationHours());t.setTicketNumber(n);t.setStockIssueDate(issue);t.setTicketNumberCycle(c);t.setExpiryDate(row.expiryDate());pending.add(t);}return tickets.saveAll(pending).stream().map(this::dto).toList();}
 private void apply(ParkingTicket t,TicketDto q,String b,boolean creating){validatePeriod(q.durationHours(),q.stockIssueDate(),q.expiryDate());LocalDate issue=q.stockIssueDate()==null?(creating?LocalDate.now():t.getStockIssueDate()):q.stockIssueDate();String c=cycle(q.durationHours(),issue,q.expiryDate());Integer n=q.ticketNumber()!=null?q.ticketNumber():(creating||!Objects.equals(c,t.getTicketNumberCycle())?nextNumber(q.durationHours(),c):t.getTicketNumber());boolean changed=creating||t.getDurationHours()!=q.durationHours()||!Objects.equals(t.getTicketNumberCycle(),c)||!Objects.equals(t.getTicketNumber(),n);if(changed&&tickets.existsByDurationHoursAndTicketNumberCycleAndTicketNumber(q.durationHours(),c,n))throw new BusinessRuleException("Ticket number "+n+" already exists for "+q.durationHours()+" hour tickets in this reset period");t.setBarcode(b);t.setPhysicalTicketNumber(clean(q.physicalTicketNumber()));t.setDurationHours(q.durationHours());t.setTicketNumber(n);t.setStockIssueDate(issue);t.setTicketNumberCycle(c);t.setExpiryDate(q.expiryDate());if(q.status()!=null)t.setStatus(q.status());}
 private String cycle(int h,LocalDate issue,LocalDate expiry){String mode=settings.value("ticketNumberResetMode","DAY").toUpperCase(Locale.ROOT);return switch(mode){case"VALIDITY"->"VALIDITY:"+issue+":"+expiry;case"DAYS"->daysCycle(issue);case"DATE_RANGE"->dateRangeCycle(issue);case"MANUAL"->"MANUAL:"+settings.manualCycle();default->"DAY:"+issue;};}
 private String daysCycle(LocalDate issue){int days=Math.max(1,Integer.parseInt(settings.value("ticketNumberResetPeriodDays","7")));LocalDate anchor=LocalDate.parse(settings.value("ticketNumberResetPeriodAnchor",LocalDate.now().toString()));long block=Math.floorDiv(ChronoUnit.DAYS.between(anchor,issue),days);LocalDate start=anchor.plusDays(block*days),end=start.plusDays(days-1L);return "DAYS:"+start+":"+end;}
 private String dateRangeCycle(LocalDate issue){LocalDate start=LocalDate.parse(settings.value("ticketNumberResetStartDate",issue.toString())),end=LocalDate.parse(settings.value("ticketNumberResetEndDate",issue.toString()));return issue.isBefore(start)||issue.isAfter(end)?"RANGE-OUTSIDE:"+issue:"RANGE:"+start+":"+end;}
 private void validatePeriod(int h,LocalDate issue,LocalDate expiry){if(!"VALIDITY".equalsIgnoreCase(settings.value("ticketNumberResetMode","DAY")))return;if(issue==null||expiry==null)throw new BusinessRuleException("Issue Date and Valid Till are required for "+h+" hour tickets. Enter the dates printed on the physical ticket.");if(expiry.isBefore(issue))throw new BusinessRuleException("Valid Till cannot be before Issue Date for "+h+" hour tickets");}
 private int nextNumber(int h,String c){Integer max=tickets.maxTicketNumber(h,c);return max==null?1:max+1;}private String normalize(String raw){String b=raw.trim();return b.regionMatches(true,0,"OGF-",0,4)?b.substring(4):b;}
 private void duplicateBarcode(String b,Long self){tickets.findByBarcodeIgnoreCase(b).filter(x->self==null||!x.getId().equals(self)).ifPresent(x->{throw new BusinessRuleException("Duplicate barcode: "+b);});}private void validate(String b,int h){if(b==null||b.isBlank())throw new BusinessRuleException("Barcode is required");if(!TYPES.contains(h))throw new BusinessRuleException("Ticket type must be 1, 2, 4, 6, 8 or 12 hours");}
 private String clean(String value){return value==null||value.isBlank()?null:value.trim();}
 private TicketDto dto(ParkingTicket t){return new TicketDto(t.getId(),t.getBarcode(),t.getPhysicalTicketNumber(),t.getDurationHours(),t.getTicketNumber(),t.getStockIssueDate(),t.getTicketNumberCycle(),t.getStatus(),t.getExpiryDate(),t.getCreatedAt(),t.getIssuedAt(),t.getIssuedToReference());}
}
