CREATE TABLE employee (id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, vehicle_number VARCHAR(40), team VARCHAR(120), department VARCHAR(120), parking_pass BOOLEAN NOT NULL DEFAULT FALSE, default_entry_time TIME);
CREATE TABLE visitor (id BIGINT AUTO_INCREMENT PRIMARY KEY, visitor_code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, nic VARCHAR(50), vehicle_number VARCHAR(40), host_department VARCHAR(160));
CREATE TABLE parking_ticket (id BIGINT AUTO_INCREMENT PRIMARY KEY, barcode VARCHAR(100) NOT NULL UNIQUE, duration_hours INT NOT NULL, status VARCHAR(30) NOT NULL, expiry_date DATE, issued_at DATETIME, issued_to_reference VARCHAR(80), version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE ticket_issue (id BIGINT AUTO_INCREMENT PRIMARY KEY, request_number VARCHAR(40) NOT NULL UNIQUE, person_type VARCHAR(20) NOT NULL, person_reference VARCHAR(40) NOT NULL, visit_date DATE NOT NULL, entry_time TIME NOT NULL, exit_time TIME NOT NULL, extra_hours INT NOT NULL DEFAULT 0, required_hours INT NOT NULL, reason VARCHAR(500), status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, completed_at DATETIME);
CREATE TABLE ticket_issue_item (id BIGINT AUTO_INCREMENT PRIMARY KEY, ticket_issue_id BIGINT NOT NULL, parking_ticket_id BIGINT NOT NULL UNIQUE, CONSTRAINT fk_issue_item_issue FOREIGN KEY(ticket_issue_id) REFERENCES ticket_issue(id), CONSTRAINT fk_issue_item_ticket FOREIGN KEY(parking_ticket_id) REFERENCES parking_ticket(id));
CREATE TABLE reconciliation (id BIGINT AUTO_INCREMENT PRIMARY KEY, reconciliation_date DATE NOT NULL, performed_at DATETIME NOT NULL, expected_available INT NOT NULL, scanned_count INT NOT NULL, missing_count INT NOT NULL, unknown_count INT NOT NULL);
CREATE TABLE reconciliation_scan (id BIGINT AUTO_INCREMENT PRIMARY KEY, reconciliation_id BIGINT NOT NULL, barcode VARCHAR(100) NOT NULL, result_status VARCHAR(30) NOT NULL, CONSTRAINT fk_recon_scan_recon FOREIGN KEY(reconciliation_id) REFERENCES reconciliation(id));
CREATE INDEX idx_ticket_status_duration ON parking_ticket(status, duration_hours);
CREATE INDEX idx_issue_status_created ON ticket_issue(status, created_at);
